map_type: costmap
origin_z: 0.0
z_resolution: 1
z_voxels: 2

obstacle_range: 2.5
raytrace_range: 3.0

publish_voxel_map: false
transform_tolerance: 0.5
meter_scoring: true

footprint_padding: 0.1

plugins:
  - { name: obstacles_layer, type: "costmap_2d::ObstacleLayer" }
  - { name: inflater_layer, type: "costmap_2d::InflationLayer" }

obstacle_layer:
  obstacle_range: 2.5
  raytrace_range: 3
  max_obstacle_height: 0.4
  track_unknown_space: true

observation_sources: point_cloud_sensorA point_cloud_sensorB

point_cloud_sensorA:
  {
    sensor_frame: base_link,
    data_type: PointCloud2,
    topic: obstacles_cloud,
    expected_update_rate: 0.5,
    marking: true,
    clearing: true,
    min_obstacle_height: 0.0,
  }

point_cloud_sensorB: {
    sensor_frame: base_link,
    data_type: PointCloud2,
    topic: ground_cloud,
    expected_update_rate: 0.5,
    marking: false,
    clearing: true,
    min_obstacle_height: -1.0, # make sure the ground is not filtered
  }
